完成booking api與booking頁面
Soniafish/taipei-day-trip-website pull request #8
Opened 2021-05-21 10:42 UTC by Soniafish

林盈如
http://3.18.227.207:3000/
http://3.18.227.207:3000/attraction/220
http://3.18.227.207:3000/booking

2021-05-21 15:47 UTC, cwpeng requested changes
我看的時候似乎後端掛掉了哦，請恢復了再和我說 ~

2021-05-21 16:42 UTC, Soniafish commented
林盈如
http://3.18.227.207:3000/
http://3.18.227.207:3000/attraction/220
http://3.18.227.207:3000/booking

2021-05-21 16:58 UTC, cwpeng requested changes
大部份都 OK，不過你的預定頁面無法確保使用者資訊先取得，再執行取得預定資訊的動作，所以有時候會出問題，這個順序必須被確保 ( 確定先取得使用者資訊、然後才取得預定行程資訊 )

請參考以下截圖，我點擊預定行程的按鈕之後，在頁面中看不到東西，有錯誤訊息
![未命名-2](https://user-images.githubusercontent.com/6104683/119172690-d66a0600-ba98-11eb-92d8-80deb2232e75.png)

2021-05-22 02:00 UTC, Soniafish commented
林盈如 （重新更正username取得時機)
http://3.18.227.207:3000/
http://3.18.227.207:3000/attraction/220
http://3.18.227.207:3000/booking

2021-05-22 15:33 UTC, cwpeng commented
資料庫連線看起來又壞掉了 @@ 一樣請恢復後和我說 ~

2021-05-22 16:17 UTC, Soniafish commented
林盈如 （重新啟動ec2了><)
http://3.18.227.207:3000/
http://3.18.227.207:3000/attraction/220
http://3.18.227.207:3000/booking

2021-05-22 17:58 UTC, cwpeng approved these changes
OK，好哦，這樣就可以了 :)

之後有額外的時間可以試著處理看看資料庫連線閒置會斷線的問題，可以用 Connection Pool 或任何你查詢到的方式來處理 ~

2021-05-22 18:24 UTC, merged